name: CI for Spring Boot Application with Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 
    steps:
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: To Show Error
        run: echo "Should fail at this point ..." ; exit 1
        
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests with Maven
        run: mvn clean install -DskipTests=false

      - name: Upload test reports
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/*.xml 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.MY_PAT_TOKEN }}

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t ghcr.io/${{ github.repository_owner }}/devops-image:latest .
      #     docker push ghcr.io/${{ github.repository_owner }}/devops-image:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_TOKEN }}

      # - name: Build Docker image
      #   run: docker build -t devops-demo-taskapp .

      # - name: Push Docker image to Docker Hub
      #   run: docker push devops-demo-taskapp


      - name: Build Docker image
        run: docker build -t ${{ secrets.MY_DOCKER_USERNAME }}/devops-demo-taskapp:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.MY_DOCKER_USERNAME }}/devops-demo-taskapp:${{ github.sha }}



  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to the production environment (Optional)
        run: |
          echo "Deployment steps here if required"
         
