name: CI for Spring Boot Application with Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests with Maven
        run: mvn clean install -DskipTests=false

      - name: Upload test reports
        if: always()  # Ensure that the report is uploaded even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/*.xml  # Maven Surefire reports (default location)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to the production environment (Optional)
        run: |
          echo "Deployment steps here if required"
         
